openapi: 3.0.0
info:
  title: 'Payment API'
  version: 1.0.0
paths:
  /projects:
    get:
      operationId: 11bd4288aa80fd77419c00230cdf92b4
      responses:
        '200':
          description: 'Display a listing of projects.'
